<?php

$file = 'mcp-1.0.0/client-cli.md';
$lines = file($file);
$updates = [
    'CLI `mcp` Subcommand' => ['to' => 'x', 'from' => 'x'],
    '`stdio` Transport Bindings' => ['to' => 'x', 'from' => 'x'],
    'Native MCP Tool Adapter' => ['to' => 'x', 'from' => 'x'],
    'Native MCP Resource Adapter' => ['to' => 'x', 'from' => 'x'],
    'LLM Execution Router' => ['to' => 'x', 'from' => 'x'],
    'SSE Endpoint Generation' => ['to' => 'x', 'from' => 'x'],
    'Dynamic API-to-Tool Proxy' => ['to' => 'x', 'from' => ' '],
    'HTTP Request/Auth Bridging' => ['to' => 'x', 'from' => 'x'],
    'Code Scaffold / Generate Tools' => ['to' => 'x', 'from' => ' '],
    'Schema Inspection Tools' => ['to' => 'x', 'from' => ' '],
    'Bidirectional Sync Tools' => ['to' => 'x', 'from' => ' '],
    'AST / Type Query Resources' => ['to' => 'x', 'from' => ' '],
    'In-Memory Generation Router' => ['to' => 'x', 'from' => ' '],
    'Standard I/O (stdio)' => ['to' => 'x', 'from' => 'x'],
    'Server-Sent Events (sse)' => ['to' => 'x', 'from' => 'x'],
    'Message Parsing & Serialization' => ['to' => 'x', 'from' => 'x'],
    'Request ID Mapping/Resolution' => ['to' => 'x', 'from' => 'x'],
    'Error Code Mapping (Standard)' => ['to' => 'x', 'from' => 'x'],
    'initialize Handshake Sequence' => ['to' => 'x', 'from' => 'x'],
    'initialized Acknowledgment' => ['to' => 'x', 'from' => 'x'],
    'Liveness (ping)' => ['to' => 'x', 'from' => 'x'],
    'Notification Handling' => ['to' => 'x', 'from' => 'x'],
    'Request Cancellation (cancelled)' => ['to' => 'x', 'from' => 'x'],
    'CancelledNotification' => ['to' => 'x', 'from' => 'x'],
    'CancelledNotification (`method`)' => ['to' => 'x', 'from' => 'x'],
    'CancelledNotification (`params`)' => ['to' => 'x', 'from' => 'x'],
    'CancelledNotification (`params`) (`reason`)' => ['to' => 'x', 'from' => 'x'],
    'CancelledNotification (`params`) (`requestId`)' => ['to' => 'x', 'from' => 'x'],

    // Objects
    'CallToolRequest' => ['to' => 'x', 'from' => 'x'],
    'CallToolRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'CallToolRequest (`params`)' => ['to' => 'x', 'from' => 'x'],
    'CallToolRequest (`params`) (`arguments`)' => ['to' => 'x', 'from' => 'x'],
    'CallToolRequest (`params`) (`name`)' => ['to' => 'x', 'from' => 'x'],
    'CallToolResult' => ['to' => 'x', 'from' => 'x'],
    'CallToolResult (`content`)' => ['to' => 'x', 'from' => 'x'],
    'CallToolResult (`isError`)' => ['to' => 'x', 'from' => 'x'],
    'ClientCapabilities' => ['to' => 'x', 'from' => 'x'],
    'ClientRequest' => ['to' => 'x', 'from' => 'x'],
    'ClientResult' => ['to' => 'x', 'from' => 'x'],
    'Implementation' => ['to' => 'x', 'from' => 'x'],
    'Implementation (`name`)' => ['to' => 'x', 'from' => 'x'],
    'Implementation (`version`)' => ['to' => 'x', 'from' => 'x'],
    'InitializeRequest' => ['to' => 'x', 'from' => 'x'],
    'InitializeRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'InitializeRequest (`params`)' => ['to' => 'x', 'from' => 'x'],
    'InitializeRequest (`params`) (`capabilities`)' => ['to' => 'x', 'from' => 'x'],
    'InitializeRequest (`params`) (`clientInfo`)' => ['to' => 'x', 'from' => 'x'],
    'InitializeRequest (`params`) (`protocolVersion`)' => ['to' => 'x', 'from' => 'x'],
    'InitializeResult' => ['to' => 'x', 'from' => 'x'],
    'InitializeResult (`capabilities`)' => ['to' => 'x', 'from' => 'x'],
    'InitializeResult (`protocolVersion`)' => ['to' => 'x', 'from' => 'x'],
    'InitializeResult (`serverInfo`)' => ['to' => 'x', 'from' => 'x'],
    'InitializedNotification' => ['to' => 'x', 'from' => 'x'],
    'InitializedNotification (`method`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCError' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCError (`error`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCError (`error`) (`code`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCError (`error`) (`message`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCError (`id`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCError (`jsonrpc`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCMessage' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCRequest' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCRequest (`id`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCRequest (`jsonrpc`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCRequest (`params`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCResponse' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCResponse (`id`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCResponse (`jsonrpc`)' => ['to' => 'x', 'from' => 'x'],
    'JSONRPCResponse (`result`)' => ['to' => 'x', 'from' => 'x'],
    'ListResourcesRequest' => ['to' => 'x', 'from' => 'x'],
    'ListResourcesRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'ListResourcesResult' => ['to' => 'x', 'from' => 'x'],
    'ListResourcesResult (`resources`)' => ['to' => 'x', 'from' => 'x'],
    'ListToolsRequest' => ['to' => 'x', 'from' => 'x'],
    'ListToolsRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'ListToolsResult' => ['to' => 'x', 'from' => 'x'],
    'ListToolsResult (`tools`)' => ['to' => 'x', 'from' => 'x'],
    'PingRequest' => ['to' => 'x', 'from' => 'x'],
    'PingRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'ReadResourceRequest' => ['to' => 'x', 'from' => 'x'],
    'ReadResourceRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'ReadResourceRequest (`params`)' => ['to' => 'x', 'from' => 'x'],
    'ReadResourceRequest (`params`) (`uri`)' => ['to' => 'x', 'from' => 'x'],
    'ReadResourceResult' => ['to' => 'x', 'from' => 'x'],
    'ReadResourceResult (`contents`)' => ['to' => 'x', 'from' => 'x'],
    'Request' => ['to' => 'x', 'from' => 'x'],
    'Request (`method`)' => ['to' => 'x', 'from' => 'x'],
    'RequestId' => ['to' => 'x', 'from' => 'x'],
    'Resource' => ['to' => 'x', 'from' => 'x'],
    'Resource (`mimeType`)' => ['to' => 'x', 'from' => 'x'],
    'Resource (`name`)' => ['to' => 'x', 'from' => 'x'],
    'Resource (`uri`)' => ['to' => 'x', 'from' => 'x'],
    'ResourceContents' => ['to' => 'x', 'from' => 'x'],
    'ResourceContents (`mimeType`)' => ['to' => 'x', 'from' => 'x'],
    'ResourceContents (`uri`)' => ['to' => 'x', 'from' => 'x'],
    'Result' => ['to' => 'x', 'from' => 'x'],
    'ServerCapabilities' => ['to' => 'x', 'from' => 'x'],
    'ServerCapabilities (`resources`)' => ['to' => 'x', 'from' => 'x'],
    'ServerCapabilities (`tools`)' => ['to' => 'x', 'from' => 'x'],
    'ServerRequest' => ['to' => 'x', 'from' => 'x'],
    'ServerResult' => ['to' => 'x', 'from' => 'x'],
    'TextContent' => ['to' => 'x', 'from' => 'x'],
    'TextContent (`text`)' => ['to' => 'x', 'from' => 'x'],
    'TextContent (`type`)' => ['to' => 'x', 'from' => 'x'],
    'TextResourceContents' => ['to' => 'x', 'from' => 'x'],
    'TextResourceContents (`mimeType`)' => ['to' => 'x', 'from' => 'x'],
    'TextResourceContents (`text`)' => ['to' => 'x', 'from' => 'x'],
    'TextResourceContents (`uri`)' => ['to' => 'x', 'from' => 'x'],
    'Tool' => ['to' => 'x', 'from' => 'x'],
    'Tool (`description`)' => ['to' => 'x', 'from' => 'x'],
    'Tool (`inputSchema`)' => ['to' => 'x', 'from' => 'x'],
    'Tool (`inputSchema`) (`properties`)' => ['to' => 'x', 'from' => 'x'],
    'Tool (`inputSchema`) (`required`)' => ['to' => 'x', 'from' => 'x'],
    'Tool (`inputSchema`) (`type`)' => ['to' => 'x', 'from' => 'x'],
    'Tool (`name`)' => ['to' => 'x', 'from' => 'x'],

    'ListPromptsRequest' => ['to' => 'x', 'from' => 'x'],
    'ListPromptsRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'ListPromptsResult' => ['to' => 'x', 'from' => 'x'],
    'ListPromptsResult (`prompts`)' => ['to' => 'x', 'from' => 'x'],
    'GetPromptRequest' => ['to' => 'x', 'from' => 'x'],
    'GetPromptRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'GetPromptRequest (`params`)' => ['to' => 'x', 'from' => 'x'],
    'GetPromptRequest (`params`) (`name`)' => ['to' => 'x', 'from' => 'x'],
    'ListResourceTemplatesRequest' => ['to' => 'x', 'from' => 'x'],
    'ListResourceTemplatesRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'ListResourceTemplatesResult' => ['to' => 'x', 'from' => 'x'],
    'ListResourceTemplatesResult (`resourceTemplates`)' => ['to' => 'x', 'from' => 'x'],
    'SetLevelRequest' => ['to' => 'x', 'from' => 'x'],
    'SetLevelRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'SetLevelRequest (`params`)' => ['to' => 'x', 'from' => 'x'],
    'SetLevelRequest (`params`) (`level`)' => ['to' => 'x', 'from' => 'x'],
    'EmptyResult' => ['to' => 'x', 'from' => 'x'],
    'CompleteRequest' => ['to' => 'x', 'from' => 'x'],
    'CompleteRequest (`method`)' => ['to' => 'x', 'from' => 'x'],
    'CompleteRequest (`params`)' => ['to' => 'x', 'from' => 'x'],
    'CompleteRequest (`params`) (`ref`)' => ['to' => 'x', 'from' => 'x'],
    'CompleteRequest (`params`) (`argument`)' => ['to' => 'x', 'from' => 'x'],
    'CompleteResult' => ['to' => 'x', 'from' => 'x'],
    'CompleteResult (`completion`)' => ['to' => 'x', 'from' => 'x'],
    'CompleteResult (`completion`) (`values`)' => ['to' => 'x', 'from' => 'x'],
    'CompleteResult (`completion`) (`hasMore`)' => ['to' => 'x', 'from' => 'x'],
];

foreach ($lines as &$line) {
    if (preg_match('/^\|\s*(\S[^\|]+?)\s*\|/', $line, $m)) {
        $feature = trim($m[1]);
        $cleanFeature = str_replace(['\*', '\\'], ['', ''], $feature);
        if (isset($updates[$feature])) {
            $to = $updates[$feature]['to'];
            $from = $updates[$feature]['from'];
            $line = preg_replace('/`\[.\]`\s*,\s*`\[.\]`/', "`[$to]` , `[$from]`", $line, 1);
        }
    }
}
file_put_contents($file, implode("", $lines));
echo "Updated $file\n";
